on: push
name: deploy
jobs:
  deploy:
    name: deploy to cluster 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: deploy to cluster
      uses: SC-Poc/kube-restart-pods@master
      env:
        KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
        NAMESPACE: common
        POD: settingsv2
